---
title: "MNIST Scorcher Example"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Fitting MNIST according to https://jtr13.github.io/cc21fall2/tutorial-on-r-torch-package.html. 


## Load data

Load the data and create the dataloader

```{r}
train_ds <- mnist_dataset(
    root = tempdir(),
    download = TRUE,
    transform = transform_to_tensor
)

dl = create_dataloader(train_ds$data |>
                         torch_tensor(dtype=torch_float()) |>
                         torch_unsqueeze(2),
                       
                       train_ds$targets |> 
                         torch_tensor(),
                       
                       batch_size = 500)
```


```{r setup}
library(scorcher)
library(torch)
library(torchvision)

scorch_model = dl |> 
  initiate_scorch() |> 
  scorch_layer(nn_conv2d(1,32,3,1)) |> 
  scorch_layer(nn_relu())|>
  scorch_layer(nn_conv2d(32,64,3,1)) |> 
  scorch_layer(nn_relu()) |>
  scorch_layer(nn_max_pool2d(2)) |> 
  scorch_layer(nn_dropout2d(0.25)) |>
  scorch_function(torch_flatten,start_dim=2) |> 
  scorch_layer(nn_linear(9216,128)) |>
  scorch_layer(nn_relu()) |> 
  scorch_layer(nn_linear(128,10))
  

compiled_scorch_model = scorch_model |>
  compile_scorch()


fitted_scorch_model = compiled_scorch_model |> 
  fit_scorch(loss=nn_cross_entropy_loss,num_epochs=2)

```

Check model

```{r}
fitted_scorch_model$eval()
b = head(dl,n=500)
output = fitted_scorch_model(b[[1]])
predicted = torch_max(output$data(),dim=2)[[2]]
labels = b[[2]]

table(predicted |> as_array(), labels |> as_array())
(predicted == labels)$sum()$item()
```

